### ISSUE TITLE
Micro-ROS Agent Communication Port issue - foxy

### ISSUE THREAD

**Issue by thihakyawjob** [micro-ROS/micro-ros-build#164]
Hi,

micro_ros_agent system has problem in foxy release. It always ask SUBCOMMAND.

> root@1aa2455843cc:/uros_ws# ros2 run micro_ros_agent micro_ros_agent udp 9999
> A subcommand is required
> Run with --help for more information.
> 
> Enter command: --help
> micro-ROS Agent
> Usage: [OPTIONS] SUBCOMMAND
> 
> Options:
>   -h,--help                               Print this help message and exit
> 
> Subcommands:
>   udp4                                    Launch a UDP/IPv4 server
>   udp6                                    Launch a UDP/IPv6 server
>   tcp4                                    Launch a TCP/IPv4 server
>   tcp6                                    Launch a TCP/IPv6 server
>   serial                                  Launch a Termios server
>   pseudoterminal                          Launch a pseudoterminal server
>   q                                       Exit
> 
> Enter command: 

Please advise me how to fix the issue.

Thanks.
Regards,
Thiha Kyaw

**Comment by pablogs9** [comment]
You should use `udp4` instead of `udp` please read the list of subcommands
