### ISSUE TITLE
Micro-ROS Agent Communication Port issue - foxy Reopen

### ISSUE THREAD

**Issue by thihakyawjob** [micro-ROS/micro-ros-build#165]
Hi,

I reopen the issue since the problem is still there.

![image](https://user-images.githubusercontent.com/12581592/89148506-a050a980-d58c-11ea-8774-9ee0b5a70e1c.png)

I did test with all subcommands. But the error is still there.

Subcommands:
udp4 Launch a UDP/IPv4 server
udp6 Launch a UDP/IPv6 server
tcp4 Launch a TCP/IPv4 server
tcp6 Launch a TCP/IPv6 server
serial Launch a Termios server
pseudoterminal Launch a pseudoterminal server
q Exit

Please see the picture.

Regards,
Thiha Kyaw

**Comment by pablogs9** [comment]
well, it says that the `--port` is required...

try with: `docker run -it --rm --net=host microros/micro-ros-agent:foxy udp4 --port 9999`
