### ISSUE TITLE
How can I use in Ros2 Dashing version？

### ISSUE THREAD

**Issue by KevinHwangAi** [micro-ROS/micro-ros-build#21]
Our team is now using Ros2-Dashing to develop robotics projects.
Could you tell me when will the dashing version be supported?

**Comment by BorjaOuterelo** [comment]
Hi @KevinHwangAi we have ported all required packages to Dashing, currently, they are under review. You should expect them to be officially ready in no more than a couple of weeks.

**Comment by KevinHwangAi** [comment]
@BorjaOuterelo This is great news. Thank you for your team's contribution.

**Comment by BorjaOuterelo** [comment]
@KevinHwangAi there is a Dashing, branch it is still on testing, but it should get you a build. I will be happy to help if you find any issue.

**Comment by KevinHwangAi** [comment]
@BorjaOuterelo  Thanks a lot! We will test it immediately.
