### ISSUE TITLE
add stm32f7 to it

### ISSUE THREAD

**Issue by chinahuangyong** [micro-ROS/micro-ros-build#35]

**Comment by iluetkeb** [comment]
Which board exactly?

**Comment by chinahuangyong** [comment]
stm32f746g-disco

**Comment by iluetkeb** [comment]
We cannot support all boards ourselves, but I've written up a tutorial on what is necessary to do.

Look at https://micro-ros.github.io/docs/tutorials/advanced/microros_nuttx_bsp/

Does that help?

**Comment by gramss** [comment]
There exists a basic Zephyr Port for this board: https://docs.zephyrproject.org/1.13.0/boards/arm/stm32f746g_disco/doc/stm32f746g_disco.html

So you should be able to port it.
Have a look at the latest commits / PRs at this repo regarding adding the nucleo_f401re board to the scripts under config/zephyr/generic and look at the int32_serial_publisher example under the micro-ROS/zephyr_apps repo. The underlying scripts should work for zephyr boards. The tricky part will be to adjust the prj.conf to your needs. But it has UART supported by the zephyr base dts, so theoretically you should get basic things working.
