### ISSUE TITLE
Introduce version numbers into config

### ISSUE THREAD

**Issue by iluetkeb** [micro-ROS/micro-ros-build#46]
Please address the comments from #41.

**Comment by julibert** [comment]
Hi @iluetkeb, we use specific commits because they point to `develop` branch and I think we should use a more stable branch. It is planning to launch a release in Micro-XRCE-DDS and then move to a tag or `master` branch.

**Comment by julibert** [comment]
Ok @iluetkeb, we are going to create a `dashing` tag in Micro-XRCE-DDS as a short term solution.
