### ISSUE TITLE
ed dependency error

### ISSUE THREAD

**Issue by julibert** [micro-ROS/micro-ros-build#76]
I'm following the instruction for compiling a NuttX configuration in a clean Docker with a Dashing distribution, and I find the following error:

```
/root/uros_ws/install/micro_ros_setup/config/nuttx/olimex-stm32-e407/create.sh: line 28: ed: command not found
```

**Comment by pablogs9** [comment]
Please remove all `apt install ed` and add the `package.xml` line when needed when https://github.com/ros/rosdistro/pull/23966 is merged

**Comment by pablogs9** [comment]
Closing because https://github.com/ros/rosdistro/pull/23966 is merged
