### ISSUE TITLE
dfu-util dependency

### ISSUE THREAD

**Issue by julibert** [micro-ROS/micro-ros-build#77]
I'm following the instruction for compiling the Crazyflie 2.1 application but the `dfu-util` dependency is not installed.

**Comment by pablogs9** [comment]
Solved here: https://github.com/micro-ROS/micro-ros-build/pull/79/files#diff-117fcd31fa40a4d80ed049b099c2cbc4R97

**Comment by pablogs9** [comment]
Close when https://github.com/micro-ROS/micro-ros-build/pull/79# merged
